name: Deploy Solution CI

on:
  push:
    branches: [ master ]
    paths:
      - terraform/**
  
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
        working-directory: ./terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      
      - name: Deploy Infra
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "ap-southeast-2"
        run: |
              ls -la
        working-directory: ${(env.working-directory)}
